import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Box, Text } from "@chakra-ui/react";
import { useTest } from "@/hooks/test";

const Home: NextPage = () => {
  const docId = "rtRTv07Cr5Lw6SfPKBHy";
  const { response } = useTest(docId);
  console.log("response", response);
  return (
    <div>
      <Head>
        <title>Latihan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Text>ini</Text>
      </Box>
    </div>
  );
};

export default Home;
